### PR TITLE
Fix two issues with post images

### PR DESCRIPTION
**Pull request by richardW8k**
- fix post image merge tags for existing images
- remove the fields old post image when a new image is saved to the
entry

### CODE REVIEW

**Comment by stevehenty** [comment]
I'm seeing an issue with the post content not updating. The form has 3 post image fields, one User Input step with one editable post image field - the other two are displayed. The post body isn't adding the new image although it's is attached to the post correctly.

**Comment by richardW8k** [comment]
Is the post body field editable? The post content is only being updated if a new value is supplied for the post body field. We could have it also update if the field isn't editable and has a content template containing merge tags.

**Comment by stevehenty** [comment]
It's editable but I left the value unchanged. So, yeah, I agree it would make sense to update the post content if it contains merge tags.

**Comment by richardW8k** [comment]
Updated to always process the content template. If a template isn't configured then the post content will only be updated if the body field has a value.

**Pull request merged**
