### PR TITLE
Add Multi-User Field

### PR DESCRIPTION
**Pull request by stevehenty**
This PR adds support for a new Multi-User field. It works like the User field.

**Testing Instructions**
- Add a Multi-User field to a form
- Make the field editable in a User Input step
- Assign an Approval step to the field
- Check the workflow works as expected
- Check the assignee policy
- Check merge tags plus modifiers work as expected
- Check export works as expected
- Check the enhanced UI
- Try to break it!

### CODE REVIEW

**Comment by richardW8k** [comment]
I'm seeing a PHP notice on form submission when a choice is selected in the field.
```
[15-Apr-2018 14:00:28 UTC] PHP Notice:  Array to string conversion in /app/public/wp-content/plugins/gravityforms/includes/fields/class-gf-field.php on line 379
[15-Apr-2018 14:00:28 UTC] PHP Stack trace:
[15-Apr-2018 14:00:28 UTC] PHP   1. {main}() /app/public/index.php:0
[15-Apr-2018 14:00:28 UTC] PHP   2. require() /app/public/index.php:17
[15-Apr-2018 14:00:28 UTC] PHP   3. wp() /app/public/wp-blog-header.php:16
[15-Apr-2018 14:00:28 UTC] PHP   4. WP->main() /app/public/wp-includes/functions.php:960
[15-Apr-2018 14:00:28 UTC] PHP   5. do_action_ref_array() /app/public/wp-includes/class-wp.php:726
[15-Apr-2018 14:00:28 UTC] PHP   6. WP_Hook->do_action() /app/public/wp-includes/plugin.php:515
[15-Apr-2018 14:00:28 UTC] PHP   7. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
[15-Apr-2018 14:00:28 UTC] PHP   8. GFForms::maybe_process_form() /app/public/wp-includes/class-wp-hook.php:286
[15-Apr-2018 14:00:28 UTC] PHP   9. GFFormDisplay::process_form() /app/public/wp-content/plugins/gravityforms/gravityforms.php:564
[15-Apr-2018 14:00:28 UTC] PHP  10. GFFormDisplay::validate() /app/public/wp-content/plugins/gravityforms/form_display.php:73
[15-Apr-2018 14:00:28 UTC] PHP  11. GFFormsModel::get_field_value() /app/public/wp-content/plugins/gravityforms/form_display.php:1677
[15-Apr-2018 14:00:28 UTC] PHP  12. Gravity_Flow_Field_Multi_User->get_value_submission() /app/public/wp-content/plugins/gravityforms/forms_model.php:2663
[15-Apr-2018 14:00:28 UTC] PHP  13. Gravity_Flow_Field_Multi_User->get_input_value_submission() /app/public/wp-content/plugins/gravityforms/includes/fields/class-gf-field.php:357
```

**Comment by stevehenty** [comment]
I've not been able to reproduce that notice on GF 2.2 or 2.3. It seems a strange line for that notice to occur.

**Comment by richardW8k** [comment]
Updating to the latest GF 2.2 build resolved the notice. No notice with 2.3.

The field merge tags ({label:id} and {label:id:value}) are returning no content when used in the form confirmation message and step instructions. 

When used in the confirmation page/redirect query string they are returning `%255B%25221%2522%255D`.

In the notification message and assignee emails {label:id} works but {label:id:value} does not. {all_fields} works but {all_fields:value} returns the labels instead of the expected values.

**Comment by stevehenty** [comment]
Thanks, should be fixed now.

**Comment by richardW8k** [comment]
`{all_fields:value} ` is now working and the `%255B%25221%2522%255D` issue in the confirmation page/redirect query string is fixed.

`{label:id:value}` still isn't returning anything.

**Pull request merged**
