### PR TITLE
Fix partial entry data loss on update and submission and update setting for GF 2.5

### PR DESCRIPTION
**Pull request by richardW8k**
## Description
re: [HS#17001](https://secure.helpscout.net/conversation/1480918751/17001?folderId=1113535)

This updates the workflow setting we add to the Partial Entries feed configuration page for compatibility with Gravity Forms 2.5. At the moment the setting remains hidden when enabling PE until the feed is saved and the page reloads. The setting, a toggle, will be displayed live for 2.5 without the page reload.

It also fixes an issue where values added to the partial entry for administrative fields by the Update Fields step (Form Connector extension) are lost when the partial entry is updated by the PE add-on.

You'll need Partial Entries v1.6.1.

## Testing instructions
- Create a form with several fields of different types e.g. text, name, address
- Set all fields except a text field as administrative
- Add an Update Fields step which is configured to update the administrative fields of the current form and entry with custom values
- Add an approval or partial entry submission step, the configuration doesn’t matter we just need it to pause the workflow
- Enable the PE add-on for the form + the workflow
- Preview form
- Add a value to the text field
- Watch the browsers network panel for ajax request to save the partial entry
- In another tab go and view the partial entry to confirm the Update Fields step has set the administrative field values
- In the preview tab change the text field value
- Wait for the ajax request to update the partial entry
- In the other tab reload the entry to confirm the text value updated and the administrative field values remained
- Check that the workflow is waiting on the second step
- In the preview tab change the text field value again and submit
- Check the entry to confirm the text value was updated and the administrative field values remained

## Automated Test Enhancements
N/A

## Documentation Changes
https://docs.gravityflow.io/article/258-partial-entries
The above page should be updated to explain that the values of non-administrative fields set by workfow steps will be lost when the partial entry is updated by the Partial Entries add-on when the heartbeat occurs, when the user pages through the form, or when the user submits the form.

## Checklist:
- [x] I've tested the code.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code follows the inline documentation standards.

### CODE REVIEW

**Review by Idealien — CHANGES_REQUESTED** [review]
When the PE step is first in workflow, test instructions work as expected. However, if there are other steps in workflow before it, this causes an infinite loop processing which does not occur when testing with master branch.

```
2021-05-16 12:02:37.681396 - DEBUG --> Gravity_Flow::process_workflow() - getting next step.
2021-05-16 12:02:37.734056 - DEBUG --> Gravity_Flow_Partial_Entries::maybe_filter_entry_pre_update(): Running for partial entry #407
2021-05-16 12:02:37.734358 - DEBUG --> Gravity_Flow_Partial_Entries::restore_fields(): Running for partial entry #407
2021-05-16 12:02:37.734671 - DEBUG --> Gravity_Flow_Partial_Entries::restore_value(): Restoring value for field #2 on partial entry update.
2021-05-16 12:02:37.734978 - DEBUG --> Gravity_Flow_Partial_Entries::restore_meta(): Running for partial entry #407
2021-05-16 12:02:37.758414 - DEBUG --> Gravity_Flow::process_workflow() - getting next step.
2021-05-16 12:02:37.767776 - DEBUG --> Gravity_Flow_Step::start() - triggered step: Partial Entry @ Start for entry id 407
2021-05-16 12:02:37.772139 - DEBUG --> Gravity_Flow_Step::is_expired() step is scheduled for expiration
2021-05-16 12:02:37.772490 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp UTC: 1621198957
2021-05-16 12:02:37.772723 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp formatted UTC: 2021-05-16 21:02:37
2021-05-16 12:02:37.772944 - DEBUG --> Gravity_Flow_Step::is_expired() current_time UTC: 1621180957
2021-05-16 12:02:37.773180 - DEBUG --> Gravity_Flow_Step::is_expired() current_time formatted UTC: 2021-05-16 16:02:37
2021-05-16 12:02:37.773399 - DEBUG --> Gravity_Flow_Step::is_expired() is expired? no
2021-05-16 12:02:37.775684 - DEBUG --> Gravity_Flow_Step::start() - Step status before processing: complete
2021-05-16 12:02:37.775999 - DEBUG --> Gravity_Flow_Step::start() - Starting step: Partial Entry @ Start
2021-05-16 12:02:37.792797 - DEBUG --> Gravity_Flow_Step::start() - step complete: yes
2021-05-16 12:02:37.793236 - DEBUG --> Gravity_Flow_Step::is_expired() step is scheduled for expiration
2021-05-16 12:02:37.793642 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp UTC: 1621198957
2021-05-16 12:02:37.793989 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp formatted UTC: 2021-05-16 21:02:37
2021-05-16 12:02:37.794312 - DEBUG --> Gravity_Flow_Step::is_expired() current_time UTC: 1621180957
2021-05-16 12:02:37.794636 - DEBUG --> Gravity_Flow_Step::is_expired() current_time formatted UTC: 2021-05-16 16:02:37
2021-05-16 12:02:37.794971 - DEBUG --> Gravity_Flow_Step::is_expired() is expired? no
2021-05-16 12:02:37.803210 - DEBUG --> Gravity_Flow_Step::is_expired() step is scheduled for expiration
2021-05-16 12:02:37.803905 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp UTC: 1621198957
2021-05-16 12:02:37.804320 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp formatted UTC: 2021-05-16 21:02:37
2021-05-16 12:02:37.804653 - DEBUG --> Gravity_Flow_Step::is_expired() current_time UTC: 1621180957
2021-05-16 12:02:37.805001 - DEBUG --> Gravity_Flow_Step::is_expired() current_time formatted UTC: 2021-05-16 16:02:37
2021-05-16 12:02:37.805325 - DEBUG --> Gravity_Flow_Step::is_expired() is expired? no
2021-05-16 12:02:37.812789 - DEBUG --> Gravity_Flow_Step::get_assignees(): assignees: Array
(
    [0] => email|testcase@example.com
)

2021-05-16 12:02:37.822098 - DEBUG --> Gravity_Flow_Step::end() - ending step 638
2021-05-16 12:02:37.824593 - DEBUG --> Gravity_Flow::process_workflow() - getting next step.
```

**Comment by saifsultanc** [comment]
@richardW8k The PE add-on is still at v1.6 for me. Any ideas when the updates will be pushed?

**Comment by richardW8k** [comment]
@saifsultanc I'm away for the rest of this month so I'm not sure when the next release is planned for. As a hotfix it will be available from the support site for manual installation or via the wp cli add-ons 'wp gf update gravityformspartialentries' command

**Comment by saifsultanc** [comment]
> When the PE step is first in workflow, test instructions work as expected. However, if there are other steps in workflow before it, this causes an infinite loop processing which does not occur when testing with master branch.
> 
> ```
> 2021-05-16 12:02:37.681396 - DEBUG --> Gravity_Flow::process_workflow() - getting next step.
> 2021-05-16 12:02:37.734056 - DEBUG --> Gravity_Flow_Partial_Entries::maybe_filter_entry_pre_update(): Running for partial entry #407
> 2021-05-16 12:02:37.734358 - DEBUG --> Gravity_Flow_Partial_Entries::restore_fields(): Running for partial entry #407
> 2021-05-16 12:02:37.734671 - DEBUG --> Gravity_Flow_Partial_Entries::restore_value(): Restoring value for field #2 on partial entry update.
> 2021-05-16 12:02:37.734978 - DEBUG --> Gravity_Flow_Partial_Entries::restore_meta(): Running for partial entry #407
> 2021-05-16 12:02:37.758414 - DEBUG --> Gravity_Flow::process_workflow() - getting next step.
> 2021-05-16 12:02:37.767776 - DEBUG --> Gravity_Flow_Step::start() - triggered step: Partial Entry @ Start for entry id 407
> 2021-05-16 12:02:37.772139 - DEBUG --> Gravity_Flow_Step::is_expired() step is scheduled for expiration
> 2021-05-16 12:02:37.772490 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp UTC: 1621198957
> 2021-05-16 12:02:37.772723 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp formatted UTC: 2021-05-16 21:02:37
> 2021-05-16 12:02:37.772944 - DEBUG --> Gravity_Flow_Step::is_expired() current_time UTC: 1621180957
> 2021-05-16 12:02:37.773180 - DEBUG --> Gravity_Flow_Step::is_expired() current_time formatted UTC: 2021-05-16 16:02:37
> 2021-05-16 12:02:37.773399 - DEBUG --> Gravity_Flow_Step::is_expired() is expired? no
> 2021-05-16 12:02:37.775684 - DEBUG --> Gravity_Flow_Step::start() - Step status before processing: complete
> 2021-05-16 12:02:37.775999 - DEBUG --> Gravity_Flow_Step::start() - Starting step: Partial Entry @ Start
> 2021-05-16 12:02:37.792797 - DEBUG --> Gravity_Flow_Step::start() - step complete: yes
> 2021-05-16 12:02:37.793236 - DEBUG --> Gravity_Flow_Step::is_expired() step is scheduled for expiration
> 2021-05-16 12:02:37.793642 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp UTC: 1621198957
> 2021-05-16 12:02:37.793989 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp formatted UTC: 2021-05-16 21:02:37
> 2021-05-16 12:02:37.794312 - DEBUG --> Gravity_Flow_Step::is_expired() current_time UTC: 1621180957
> 2021-05-16 12:02:37.794636 - DEBUG --> Gravity_Flow_Step::is_expired() current_time formatted UTC: 2021-05-16 16:02:37
> 2021-05-16 12:02:37.794971 - DEBUG --> Gravity_Flow_Step::is_expired() is expired? no
> 2021-05-16 12:02:37.803210 - DEBUG --> Gravity_Flow_Step::is_expired() step is scheduled for expiration
> 2021-05-16 12:02:37.803905 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp UTC: 1621198957
> 2021-05-16 12:02:37.804320 - DEBUG --> Gravity_Flow_Step::is_expired() expiration_timestamp formatted UTC: 2021-05-16 21:02:37
> 2021-05-16 12:02:37.804653 - DEBUG --> Gravity_Flow_Step::is_expired() current_time UTC: 1621180957
> 2021-05-16 12:02:37.805001 - DEBUG --> Gravity_Flow_Step::is_expired() current_time formatted UTC: 2021-05-16 16:02:37
> 2021-05-16 12:02:37.805325 - DEBUG --> Gravity_Flow_Step::is_expired() is expired? no
> 2021-05-16 12:02:37.812789 - DEBUG --> Gravity_Flow_Step::get_assignees(): assignees: Array
> (
>     [0] => email|testcase@example.com
> )
> 
> 2021-05-16 12:02:37.822098 - DEBUG --> Gravity_Flow_Step::end() - ending step 638
> 2021-05-16 12:02:37.824593 - DEBUG --> Gravity_Flow::process_workflow() - getting next step.
> ```

Wasn't able to replicate this behaviour

**Review by saifsultanc — COMMENTED** [review]
Works as expected as per the testing instructions.

**Review by Idealien — APPROVED** [review]
Functionality works as expected in both 'PE as first step' and in subsequent locations through the workflow. Only thing missing is a change_log.txt update.

**Pull request merged**
